packages:
  - 'packages-api/**'
  - 'packages-components/**'
  - 'packages-ssg/**'
  - 'packages-widgets/**'
  - 'packages-shared/**'
  - 'packages-trade/**'
  - 'packages-deploy/**'
  - 'packages-web3/**'
  - 'packages-ws/**'
