packages:
  # all packages in subdirs of packages/ and components/
  - 'packages/**'
  - 'packages-echarts/**'
  - 'packages-shared/**'
  - 'packages-ssg/**'
  - 'packages-trade/**'
  - 'packages-web3/**'
  - 'packages-widgets/**'
  - 'packages-deploy/**'
  - 'scripts'
