export const data: any = {
  Live: [
    {
      No: 1,
      Pool: 'mSOL-ULP',
      Range: '-',
      LP: '10.000(8.000) SOL',
      Currency: 'SOL',
      'Earned Fees': 0.5,
      feeCurrency: 'SOL',
      'Awarded RTX': 5,
      APR: '10.12%',
      Liquidity: null,
    },
    {
      No: 2,
      Pool: 'jitoSOL-2512',
      Range: '6.00%-8.00%',
      LP: '5.000(4.500) SOL',
      Currency: 'SOL',
      'Earned Fees': 0.3,
      feeCurrency: 'SOL',
      'Awarded RTX': 3,
      APR: '8.67%',
      Liquidity: null,
    },
    {
      No: 3,
      Pool: 'USDY-2606',
      Range: '3.00%-5.00%',
      LP: '5.000(4.500) USD',
      Currency: 'USD',
      'Earned Fees': 0.2,
      feeCurrency: 'USDY',
      'Awarded RTX': 2,
      APR: '6.54%',
      Liquidity: null,
    },
  ],
};
