import '@rx-ssg/account';
import '@rx-ssg/liquidity';
import '@rx-ssg/main';
import '@rx-ssg/strategy';
import '@rx/helper/polyfill/EventTarget';
import '@rx/helper/polyfill/array';
import '@rx/helper/polyfill/map';
import '@rx/helper/polyfill/rxjs';
import 'virtual:uno.css';
